### PR TITLE
Update FMA

### PR DESCRIPTION
**Pull request by msimecek**
WIP pull request to continuously update the failure analysis as we discuss chaos experiments.

### CODE REVIEW

**Comment by msimecek** [comment]
No updates for several weeks, let's do a final review and get rid of this PR :)

**Comment by heoelri** [comment]
Sorry, I haven't had that in mind. How do we want to proceed with this PR? @sebader? We've the original content (prior to this PR) here: https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks-mission-critical/mission-critical-health-modeling#failure-analysis

**Comment by sebader** [comment]
probably makes sense to move this to a PR in docs?!

**Comment by msimecek** [comment]
Yeah, doesn't make sense to restore the file in GH.

**Comment by msimecek** [comment]
https://github.com/MicrosoftDocs/architecture-center-pr/pull/7854

**Pull request closed without merging**
