### PR TITLE
Update arch-diagram 

### PR DESCRIPTION
**Pull request by hjscherer**
Remove PE on the architecture diagram for the online RI

### CODE REVIEW

**Review by sebader — CHANGES_REQUESTED** [review]
the resolution gets lower every time. could you increase it a bit?

**Comment by hjscherer** [comment]
> the resolution gets lower every time. could you increase it a bit?

Will move to SVG for better resolution. Did that already a while ago on the connected diagram

**Review by sebader — APPROVED** [review]
thanks for this!

**Review by heoelri — APPROVED** [review]
LGTM

**Comment by heoelri** [comment]
> What is the status of this PR? Is this still relevant? @hjscherer Hansjoerg Scherer FTE / @sebader Sebastian Bader FTE

Ah, I see. Depends on the CODEOWNERS update.

**Review by CalCof — APPROVED** [review]

**Pull request merged**
