### PR TITLE
scale down INT AKS nodes

### PR DESCRIPTION
**Pull request by sebader**

### CODE REVIEW

**Review by msimecek — APPROVED** [review]

**Comment by heoelri** [comment]
Can all our pods run on a single node?

**Comment by heoelri** [comment]
> Can all our pods run on a single node?

Asking cause otherwise it will scale out to 2 or three anways.

**Comment by sebader** [comment]
> Can all our pods run on a single node? 

Actually e2e is also set to one but I believe it always runs on 2 nodes :)

**Comment by sebader** [comment]
But yeah good point, maybe we should just set both to 2 to start with

**Comment by heoelri** [comment]
I assume the reason is the current quota limitation, right? The new request form does still not work and the support ticket wasn't processed yet.

image

**Comment by sebader** [comment]
> I assume the reason is the current quota limitation, right? The new request form does still not work and the support ticket wasn't processed yet.
> 
> image

yeah, I also tried that :( 

what do you think, should we set the minimum for both e2e and int to 2nodes since that seems to be what we require anyway?

**Pull request merged**
