### PR TITLE
Simplify helm chart installation

### PR DESCRIPTION
**Pull request by heoelri**
Helm 3.x does now finally support the creation of not existing namespaces, again this was already the case in Helm 2.x.

This PR simplifies the installation via `helm upgrade` by using `--create-namespace` to create the target namespace (if not exist) w/o the need for an additional `kubectl apply` statement.

**DRAFT** - Waiting for proper testing till the issue with the ingress path was fixed. https://helm.sh/docs/helm/helm_install/

### CODE REVIEW

**Comment by heoelri** [comment]
Testing it here: https://dev.azure.com/mission-critical/Online/_build/results?buildId=1134&view=results

**Comment by sebader** [comment]
is this ready to merge now?

**Comment by heoelri** [comment]
> is this ready to merge now?

Yes, the e2e run was successful and is getting destroyed now.

**Review by sebader — APPROVED** [review]
LGTM

**Pull request merged**
