### PR TITLE
Update Grafana to 9.0.4

### PR DESCRIPTION
**Pull request by heoelri**
This PR updates Grafana from `8.3.4` to `9.0.4`. Grafana `>=8.3.5` (and newer) require a CSRF configuration to make it work behind Azure Front Door. This is set via Terraform:

```
"GF_SECURITY_CSRF_ADDITIONAL_HEADERS" = "X-FORWARDED-HOST"
"GF_SECURITY_CSRF_TRUSTED_ORIGINS" = "https://${var.frontdoor_fqdn}"
```

image

@nielsams would you mind taking a look? Thanks!

### CODE REVIEW

**Review by sebader — APPROVED** [review]
LGTM

**Comment by nielsams** [comment]
LGTMT!

**Comment by sebader** [comment]
please port to Connected, too

**Comment by heoelri** [comment]
Ah, I haven't had that on my radar that this is in connected as well.

**Pull request merged**
